[workspace]
members = [
	"agent",
	"agent-client",
	"client",
	"common",
	"downstairs",
	"hammer",
	"nbd_server",
	"protocol",
	"scope",
	"smf",
	"upstairs",
]

[patch."https://github.com/oxidecomputer/progenitor"]
progenitor = { path = "../progenitor/progenitor" }
